version: "3.8"

services:
  patient-service-db:
    image: postgres:16-alpine
    container_name: patient-service-db-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patientdb
    ports:
      - "5434:5432"
    volumes:
      - patient-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - microservice-net

  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-service
    depends_on:
      patient-service-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patientdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_APPLICATION_NAME: patient-service
      SERVER_PORT: 4000

      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
#    ports:
#      - "4000:4000"
    restart: on-failure
    networks:
      - microservice-net

volumes:
  patient-db-data:

networks:
  microservice-net:
    external: true
